// In-app admin password recovery.
//
// Public (no JWT) endpoint that lets a locked-out administrator reset their
// own password using either:
//   1) A pre-shared ADMIN_RECOVERY_PASSPHRASE held server-side, or
//   2) An unused MFA backup code previously generated by that admin.
//
// Per security policy, this flow does NOT clear `account_locked` or
// `failed_login_attempts` — the existing admin-unlock workflow handles that.
//
// CSRF, origin allow-list, length caps, constant-time passphrase compare,
// 8-second sleep on failure to slow brute force.
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.49.4";
import { assertCsrfSafe, csrfDeniedResponse } from "../_shared/csrf.ts";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type, x-cybernet-app",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
};

function timingSafeEqual(a: string, b: string): boolean {
  const ab = new TextEncoder().encode(a);
  const bb = new TextEncoder().encode(b);
  if (ab.length !== bb.length) return false;
  let diff = 0;
  for (let i = 0; i < ab.length; i++) diff |= ab[i] ^ bb[i];
  return diff === 0;
}

function passwordOk(p: unknown): p is string {
  if (typeof p !== "string" || p.length < 12 || p.length > 128) return false;
  return /[a-z]/.test(p) && /[A-Z]/.test(p) && /\d/.test(p) && /[^A-Za-z0-9]/.test(p);
}

const json = (status: number, body: unknown) =>
  new Response(JSON.stringify(body), {
    status,
    headers: { ...corsHeaders, "Content-Type": "application/json" },
  });

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });
  if (req.method !== "POST") return json(405, { error: "Method not allowed" });

  const csrf = assertCsrfSafe(req);
  if (!csrf.ok) return csrfDeniedResponse(corsHeaders, csrf.reason);

  const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
  const serviceKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
  const passphrase = Deno.env.get("ADMIN_RECOVERY_PASSPHRASE") ?? "";
  const admin = createClient(supabaseUrl, serviceKey);

  const body = await req.json().catch(() => null) as
    | { staff_id?: string; method?: string; secret?: string; new_password?: string }
    | null;
  if (!body) return json(400, { error: "Invalid JSON" });

  const staffId = String(body.staff_id ?? "").trim();
  const method = String(body.method ?? "");
  const secret = String(body.secret ?? "");
  const newPassword = body.new_password;

  if (!staffId || staffId.length > 64) return json(400, { error: "staff_id required" });
  if (method !== "passphrase" && method !== "backup_code") return json(400, { error: "method must be 'passphrase' or 'backup_code'" });
  if (!secret || secret.length > 256) return json(400, { error: "secret required" });
  if (!passwordOk(newPassword)) {
    return json(400, { error: "Password must be 12+ chars and include upper, lower, number and symbol." });
  }

  const ip = req.headers.get("x-forwarded-for")?.split(",")[0]?.trim() ?? null;
  const ua = req.headers.get("user-agent") ?? null;

  // Look up the profile by staff_id (case-insensitive).
  const { data: profile, error: profErr } = await admin
    .from("profiles")
    .select("id, user_id, staff_id, first_name, last_name, email")
    .ilike("staff_id", staffId)
    .maybeSingle();

  if (profErr || !profile?.user_id) {
    await new Promise((r) => setTimeout(r, 8000));
    await admin.from("system_audit_log").insert({
      action: "admin_recovery_failed",
      entity_type: "profiles",
      entity_id: null,
      performed_by: null,
      details: { staff_id: staffId, method, reason: "profile_not_found", ip, ua },
    }).then(() => {}).catch(() => {});
    return json(401, { error: "Recovery failed" });
  }

  // Confirm target is admin.
  const { data: roles } = await admin
    .from("user_roles")
    .select("role")
    .eq("user_id", profile.user_id);
  const isAdmin = (roles ?? []).some((r: any) => r.role === "admin");
  if (!isAdmin) {
    await new Promise((r) => setTimeout(r, 8000));
    await admin.from("system_audit_log").insert({
      action: "admin_recovery_denied",
      entity_type: "profiles",
      entity_id: profile.id,
      performed_by: null,
      details: { staff_id: staffId, method, reason: "not_admin", ip, ua },
    }).then(() => {}).catch(() => {});
    return json(403, { error: "Recovery only available for administrator accounts" });
  }

  // Verify the chosen second factor.
  let verified = false;
  if (method === "passphrase") {
    if (passphrase.length === 0) {
      return json(503, { error: "Recovery passphrase not configured on server" });
    }
    verified = timingSafeEqual(secret, passphrase);
  } else {
    const { data, error } = await admin.rpc("admin_recovery_consume_backup_code", {
      _user_id: profile.user_id,
      _code: secret,
    });
    if (error) {
      return json(500, { error: "Recovery check failed" });
    }
    verified = data === true;
  }

  if (!verified) {
    await new Promise((r) => setTimeout(r, 8000));
    await admin.from("system_audit_log").insert({
      action: "admin_recovery_failed",
      entity_type: "profiles",
      entity_id: profile.id,
      performed_by: null,
      details: { staff_id: staffId, method, reason: "bad_secret", ip, ua },
    }).then(() => {}).catch(() => {});
    return json(401, { error: "Recovery failed" });
  }

  // Apply the new password and force a change on next login.
  const { error: updErr } = await admin.auth.admin.updateUserById(profile.user_id, {
    password: newPassword,
    user_metadata: { must_change_password: true },
  });
  if (updErr) return json(500, { error: updErr.message });

  // Sign out any active sessions for this user.
  await admin.auth.admin.signOut(profile.user_id).then(() => {}).catch(() => {});

  // Clear lockout state so the admin can sign in immediately. Without this,
  // a sole admin who is locked out has no way back in. Both actions are
  // audited so the trail remains intact.
  let lockoutCleared = false;
  try {
    await admin.rpc("clear_failed_login_attempts", { _staff_id: profile.staff_id });
    const { error: unlockErr } = await admin
      .from("profiles")
      .update({ account_locked: false })
      .eq("id", profile.id);
    lockoutCleared = !unlockErr;
  } catch { /* best-effort */ }

  await admin.from("system_audit_log").insert({
    action: "admin_recovery_succeeded",
    entity_type: "profiles",
    entity_id: profile.id,
    performed_by: profile.user_id,
    details: {
      staff_id: profile.staff_id,
      target_name: `${profile.first_name} ${profile.last_name}`,
      method,
      lockout_cleared: lockoutCleared,
      ip,
      ua,
    },
  }).then(() => {}).catch(() => {});

  return json(200, {
    ok: true,
    staff_id: profile.staff_id,
    must_change_password: true,
    lockout_cleared: lockoutCleared,
    note: lockoutCleared
      ? "Password reset and account lockout cleared. You can sign in now."
      : "Password reset. Lockout state could not be auto-cleared — use the admin unlock workflow.",
  });
});
