import { useQuery } from "@tanstack/react-query";
import { Info, RefreshCw, History } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { useBuildRelease } from "@/hooks/useBuildRelease";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { APP_VERSION, BUILD_TIME } from "@/lib/build-version";
import { formatDate, formatDateTime } from "@/lib/date-format";

interface ReleaseRow {
  id: string;
  version_id: string;
  build_date: string;
  seq: number;
  app_version: string | null;
  build_time: string;
  first_seen_at: string;
}

/**
 * Current build identity plus the automatically recorded deployment history.
 * The version identifier (ITIDDMMYYYY-NN) is generated by the backend on the
 * first load after each deployment — it is never edited by hand.
 */
export function SystemInformationPanel() {
  const build = useBuildRelease();

  const history = useQuery({
    queryKey: ["app-build-releases"],
    queryFn: async (): Promise<ReleaseRow[]> => {
      const { data, error } = await (supabase as any)
        .from("app_build_releases")
        .select("id, version_id, build_date, seq, app_version, build_time, first_seen_at")
        .order("build_date", { ascending: false })
        .order("seq", { ascending: false })
        .limit(50);
      if (error) throw error;
      return (data ?? []) as ReleaseRow[];
    },
    staleTime: 60_000,
  });

  return (
    <Card>
      <CardHeader className="pb-3">
        <div className="flex flex-wrap items-start justify-between gap-3">
          <div>
            <CardTitle className="flex items-center gap-2 text-base">
              <Info className="h-4 w-4 text-primary" /> System information
            </CardTitle>
            <CardDescription>
              Build identity and deployment history. Version identifiers are generated automatically
              after every successful deployment.
            </CardDescription>
          </div>
          <Button variant="secondary" size="sm" onClick={() => void history.refetch()}>
            <RefreshCw className="mr-2 h-4 w-4" /> Refresh
          </Button>
        </div>
      </CardHeader>
      <CardContent className="space-y-5">
        <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
          <Field label="Current build">
            <span className="font-mono text-sm" title={build.tooltip}>{build.versionId}</span>
            {!build.registered && (
              <Badge variant="outline" className="ml-2 text-[10px]">pending</Badge>
            )}
          </Field>
          <Field label="App version">v{APP_VERSION}</Field>
          <Field label="Built">{formatDateTime(build.release?.build_time ?? BUILD_TIME)}</Field>
          <Field label="First seen">
            {build.release?.first_seen_at ? formatDateTime(build.release.first_seen_at) : "—"}
          </Field>
        </div>

        <div className="space-y-2">
          <h4 className="flex items-center gap-2 text-sm font-semibold">
            <History className="h-4 w-4 text-muted-foreground" /> Deployment history
          </h4>
          <div className="overflow-x-auto rounded-md border">
            <Table className="min-w-[700px]">
              <TableHeader>
                <TableRow>
                  <TableHead>Version</TableHead>
                  <TableHead>Build date</TableHead>
                  <TableHead className="text-right">Sequence</TableHead>
                  <TableHead>App version</TableHead>
                  <TableHead>Built</TableHead>
                  <TableHead>First seen</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {history.isLoading && (
                  <TableRow><TableCell colSpan={6} className="text-muted-foreground">Loading deployment history…</TableCell></TableRow>
                )}
                {!history.isLoading && (history.data?.length ?? 0) === 0 && (
                  <TableRow><TableCell colSpan={6} className="text-muted-foreground">No deployments recorded yet.</TableCell></TableRow>
                )}
                {(history.data ?? []).map((r) => (
                  <TableRow key={r.id} className={r.version_id === build.versionId ? "bg-muted/40" : undefined}>
                    <TableCell className="font-mono text-xs">{r.version_id}</TableCell>
                    <TableCell>{formatDate(r.build_date)}</TableCell>
                    <TableCell className="text-right tabular-nums">{String(r.seq).padStart(2, "0")}</TableCell>
                    <TableCell>{r.app_version ? `v${r.app_version}` : "—"}</TableCell>
                    <TableCell className="whitespace-nowrap">{formatDateTime(r.build_time)}</TableCell>
                    <TableCell className="whitespace-nowrap">{formatDateTime(r.first_seen_at)}</TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </div>
        </div>
      </CardContent>
    </Card>
  );
}

function Field({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <div className="rounded-md border bg-muted/30 p-3">
      <div className="text-[11px] uppercase tracking-wide text-muted-foreground">{label}</div>
      <div className="mt-1 text-sm font-medium">{children}</div>
    </div>
  );
}
